name = "StrainedElectronicDevices"
uuid = "b216b5de-52e9-47ff-b90b-2c83c7be6265"
version = "1.0.0"
authors = ["Patrick Jaap <patrick.jaap@wias-berlin.de>"]

[deps]
AMGCLWrap = "4f76b812-4ba5-496d-b042-d70715554288"
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"

[sources]
ExtendableFEM = {rev = "fix/verbosity", url = "https://github.com/WIAS-PDELib/ExtendableFEM.jl"}
ExtendableSparse = {rev = "feature/Schurcomplement_precon", url = "https://github.com/WIAS-PDELib/ExtendableSparse.jl"}

[compat]
AMGCLWrap = "2.1.0"
Aqua = "0.8.14"
ExplicitImports = "1.15.0"
ExtendableFEM = "1.9.0"
ExtendableGrids = "1.15.0"
ExtendableSparse = "2.1.0"
ForwardDiff = "1.3.1"
GridVisualize = "1.17.0"
ILUZero = "0.2.0"
JLD2 = "0.6.3"
Krylov = "0.10.4"
LinearAlgebra = "1.10"
LinearSolve = "3.57.0"
Pardiso = "1.1.2"
SimplexGridFactory = "2.6.1"
StaticArrays = "1.9.16"
Test = "1.10"
TetGen = "2.0.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "Test"]
